### ISSUE TITLE
What am i doing wrong?

### ISSUE THREAD

**Issue by Kribli-krabli** [idlesign/sponsrdump#1]
user@ubuntu:~/Sponsor$ python3 ./sponsrdump.py "https://sponsr.ru/uzhukoffa_lessons/" --title "Урок 1" --to here/ --prefer-video 640x360 --text-to-video
Traceback (most recent call last):
  File "/home/papa/Sponsor/./sponsrdump.py", line 653, in <module>
    dumper = SponsrDumper(args.project_url)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/papa/Sponsor/./sponsrdump.py", line 128, in __init__
    self._auth_read()
  File "/home/papa/Sponsor/./sponsrdump.py", line 458, in _auth_read
    dict(
ValueError: dictionary update sequence element #0 has length 1; 2 is required

**Comment by idlesign** [comment]
Most probably you'd copied a trailing semicolon along with `SESS=...`. 
In other words: there should be no semicolon in `sponsrdump_auth.txt`.

**Comment by idlesign** [comment]
I've handle this kind of error in code. Feel free to update and reopen the issue if required.

**Comment by Kribli-krabli** [comment]
I didn't find a semicolon in SESS, I copied its value using the cookie-editor chrome extension, maybe it adds its own characters? How long should SESS be? Mine have 356 simbols.
